### ISSUE TITLE
Migrating second time without removing Joomla 2.5 throws error

### ISSUE THREAD

**Issue by mahagr** [fastslack/jUpgrade#13]
GET templates_files.php:

<br /><b>jos-Error</b>: JLIB_FILESYSTEM_ERROR_FOLDER_EXISTS<br />
<br /><b>jos-Error</b>: JLIB_FILESYSTEM_ERROR_FOLDER_EXISTS<br />
<br /><b>jos-Error</b>: JLIB_FILESYSTEM_ERROR_FOLDER_EXISTS<br />
<br /><b>jos-Error</b>: JLIB_FILESYSTEM_ERROR_FOLDER_EXISTS<br />

GET migrate_files.php:

<br /><b>jos-Error</b>: JLIB_FILESYSTEM_ERROR_FOLDER_EXISTS<br />

GET extensions_controller.php (akeeba, kunena and others):

<br /><b>jos-Error</b>: JLIB_FILESYSTEM_ERROR_FOLDER_EXISTS<br />

**Comment by mahagr** [comment]
Looks like there's a side effect for this bug:

If you have updated your Joomla 1.5 installation (or users have uploaded new files), those won't be copied to the new installation.

**Comment by fastslack** [comment]
That error is returned by the JFolder class if you re-run the installation and the destination directory was already copied before. You must to remove the destination directory and re-run jupgrade again

**Comment by mahagr** [comment]
Yes, but should we automate that? Because of all users do the same mistake and there's no indication that something goes wrong -- at least if you don't look into JSON replies. So people think that everything goes well and gets imported, but that's not true, they end up having old copy of their site if they have forgotten to delete the directory.

**Comment by fastslack** [comment]
I think that the solution is to move the destination directories because this directories maybe can be modified too so we cant to delete it every time that jupgrade runs..

**Comment by mahagr** [comment]
I'm just thinking of the use case - normally you just want to migrate your site to new one. If you tried it a week ago, you may try to do it again now.

I would add a new option that automatically deletes new installation -- unless you turn it off. Another way is to work around this Joomla limitation and update existing files with new ones instead of just failing.

**Comment by mahagr** [comment]
This is related to #19

**Comment by fastslack** [comment]
Fixed on bc3a6a817310b271b0ac4032b63322da983b6926
