### ISSUE TITLE
Upgrade brings new ID's to Menus, articles, etc.

### ISSUE THREAD

**Issue by Djdiskis** [fastslack/jUpgrade#15]
Hello,

I still have got an Joomla 1.5.25 version running and I'm tryning now for two days already to upgrade to Joomla 2.5.
BUT the whole website crashes due to the change of id's.

I read somewhere it is the reason that there are different default id's with the new 2.5 version.

Shouldn't the Jupgrade tool prevent such errors? 
Would it be possible to upgrade and remain ALL old id's and just add the "default" ones to the back.

For that reason it would be much easier to upgrade and older Joomla version.

Thanks in advance.

**Comment by fastslack** [comment]
Im working on this, hope to have a patch soon..
Regards

**Comment by Djdiskis** [comment]
Hey fastslack, what a fast response from your site. I really didn't expect that! Thanks

That would be so awesome! Thank you very much for Jupgrade! It was really easy to update to 2.5.
Just the mess with the id's made the site not viewable anymore ;)

Thank you in advance!

**Comment by Djdiskis** [comment]
Hey fastslack, any progress already on fixing that issue?

**Comment by fastslack** [comment]
Hi Djdiskis,

Try with this change f3a5b4455b4bf79109b2304b800da70bfb1126b7

The id 1 is used by root but the we are keeping the others.

**Comment by Djdiskis** [comment]
Hey Fastslack,
this version doesn't work at all anymore.
I just tried it.
1. if you want to change the settings the old popup is gone, it open in itself. and you cannot close it.
2. if you open jupgrade it shows already every process without the red diagram. and already "finished button" but it couldnt be finished.
3. if you click on Upgrade, it doesnt do anything.

**Comment by fastslack** [comment]
Mmmm how you tested it? 

This fix not change any more than the menu migration, the rest is the same so is very strange that broke all the component. Please check if you have Mootools 1.2.4 or greater enabled in your site.

Take care

**Comment by Djdiskis** [comment]
EDIT: Ok other site worked, dont know what went wrong

**Comment by Djdiskis** [comment]
Ok now it worked with the menu.
But could you do a fix for the articles as well?
I got like 600 articles ID's and some are "fixed" on a menu on my 1.5 website.
If now all articles get a new id than there is different article behind the menu link.

Is it possible to stick to the old ID numbers as well?

**Comment by fastslack** [comment]
Hmmmm the articles keeps the same id too..

**Comment by Djdiskis** [comment]
You mean they should after your fix?
I can say they dont :P
If you wanna see it i can show you via teamviewer or so. Dont know, if i do anything wrong.

**Comment by Djdiskis** [comment]
Would it be easy to keep the id's of the articles as well?

**Comment by fastslack** [comment]
Yes is more easy.. I thought it was working.. 
Try with this patch 7b18b0f16f727bc0ea19797ab96be95becf52729

**Comment by Djdiskis** [comment]
Thank you very much! It worked! 
Now i just need the old extentions to be upgraded to 2.5 as well =)

Awesome extension!!!! I really appriciate it!
