### ISSUE TITLE
Banners not migrated correctly

### ISSUE THREAD

**Issue by Kriechi** [fastslack/jUpgrade#17]
Hey,

it seems to me, that the banners are not correctly migrated.
- category is not set (e.g. zero)
- client is not set (e.g. zero)
- image-path is not set (e.g. empty)

EDIT:
concerning image-path:
seems that the sql-layout is wrong in migrate-banners.php:getSourceData()

$rows = parent::getSourceData(
                        '`bid` AS id, `cid`, `type`, `name`, `alias`, `imptotal` ,`impmade`, `clicks`, '
                        .'`catid`, `clickurl`, `checked_out`, `checked_out_time`, `showBanner` AS state, '
                        .'`custombannercode`, `description`, `sticky`, `ordering`, `publish_up`, '
                        .'`publish_down`, `params`', null, 'bid');

should be:

$rows = parent::getSourceData(
                        '`bid` AS id, `cid`, `type`, `name`, `alias`, `imptotal`, `impmade`, '
                        .'`clicks`, `imageurl`, `clickurl`, `date`, `showBanner` AS state, `checked_out`, '
                        .'`checked_out_time`, `editor`, `custombannercode`, `catid`, `description`, '
                        .'`sticky`, `ordering`, `publish_up`, `publish_down`, `tags`, `params`', null, 'bid'); 

imageurl must then be set as key-value pair in params.

**Comment by fastslack** [comment]
Applied your pull request, thanks
