### ISSUE TITLE
Database doesn't get updated to J2.5.1

### ISSUE THREAD

**Issue by mahagr** [fastslack/jUpgrade#20]
Go to Extensions > Extension Manager > Database

Warning: Database is not up to date!
Database schema version (None) does not match CMS version (2.5.1).

**Comment by Kriechi** [comment]
Seems to be not a big issue, because Joomla itself can fix it. (button in the upper-right corner).
Only difference seems to be a version-string set to version-number and build-date.
Seems not very important.

**Comment by mahagr** [comment]
If you're upgrading more than one site, you forget to check bugs like this. So it is an issue as the site mostly works without the changes (but not always). It shouldn't be hard to fix either...

**Comment by mahagr** [comment]
Check administrator/components/com_installer/models/database.php:

```
$folder = JPATH_ADMINISTRATOR . '/components/com_admin/sql/updates/';
$changeSet = JSchemaChangeset::getInstance(JFactory::getDbo(), $folder);
$changeSet->fix();

// Get correct schema version -- last file in array
$schema = $changeSet->getSchema();
$db = JFactory::getDbo();

// Delete old row
$query = $db->getQuery(true);
$query->delete($db->qn('#__schemas'));
$query->where($db->qn('extension_id') . ' = 700');
$db->setQuery($query);
$db->query();

// Add new row
$query = $db->getQuery(true);
$query->insert($db->qn('#__schemas'));
$query->set($db->qn('extension_id') . '= 700');
$query->set($db->qn('version_id') . '= ' . $db->q($schema));
$db->setQuery($query);
```

Above code should update Joomla database to the latest version.

**Comment by Kriechi** [comment]
I think it would be safer to just run the InstallerModelDatabase::fix()-method of the new installation.
But I'm not quite sure how to acces that code from outside (the old installation).

**Comment by fastslack** [comment]
Please check this patch: edde23319dd59a0862577601b2ea389dba1d4b56

**Comment by Kriechi** [comment]
Yes, that works.

**Comment by mahagr** [comment]
Yes, this works.
