### ISSUE TITLE
Extra modules enabled after migration

### ISSUE THREAD

**Issue by mahagr** [fastslack/jUpgrade#21]
There are 3 extra modules compared to the original site:
- Breadcrumbs (position-2)
- Main Menu (position-7)
- Login Form (position-7)

**Comment by fastslack** [comment]
Check this patch: 92e7c8580d288fa8b5c4d16232468931374e6e32

We really should disable the default Main menu?

**Comment by mahagr** [comment]
That's the default menu from Joomla. Migration brings another menu module with the same name.

**Comment by fastslack** [comment]
ok, closing this issue
