### ISSUE TITLE
Module menu assigments are broken

### ISSUE THREAD

**Issue by mahagr** [fastslack/jUpgrade#23]
Latest fixes seem to break module assignments when they were attached only to some menu items. Result is that every assignment that wasn't 'All' becomes 'None'. So the menu mapping code is still needed -- if only for Itemid=1 (and rest being x => x).

**Comment by fastslack** [comment]
Id's mapping reverted as discussed: 3ab7cb3136fb4ecfdba471c6934027a5361a94dd

**Comment by mahagr** [comment]
Will check it tomorrow.

**Comment by mahagr** [comment]
Mostly works. Just item which had id=1 (Main menu) doesn't get menu assigment (=All).

**Comment by mahagr** [comment]
I tried to look into the code, but I'm not sure why menu item 0 doesn't work. I always have to enable main menu by hand after doing the migration.

**Comment by mahagr** [comment]
@fastslack What are the rest of the modules which aren't getting menu assigments (see diff)?
