### ISSUE TITLE
jUpgrade 2.5.1 banner migration not working properly

### ISSUE THREAD

**Issue by rasharon** [fastslack/jUpgrade#27]
Symptoms:

Only some banner categories are migrated.  

NO clients are migrated

I don't know if this is a Joomla or jUpgrade data corruption problem: when I add back a single client row that has multiple banners, the Joomla banner client display lists it multiple times. I'm guessing it is joining to another table that has multiple rows for that client thus causing the repeated rows.

**Comment by grantiago** [comment]
I'm seeing this as well . joomla 2.5.3. multiple rows of  clients and no banners showing.

**Comment by rasharon** [comment]
I was able to reverse engineer the database then:
Use custom SQL queries to migrate ALL banner clients (NONE of them were copied over by the migration).
Use custom SQL queries to migrate categories that did not get migrated (not just Banner categories, I also had to do that for article categories, contact categories, weblink categories, newsfeed categories.  No docman categories were migrated but apparently docman no longer uses the Joomla category table, uses its own category table and their migration export/import DID work).  

I discovered several articles somehow got mapped to banner categories instead of their proper article categories, so I had to  move them back to the correct categories using Article Manager's mass move.  

NONE of my banners would display.  All of my banners were using custom code and the migration apparently hard codes them to not be "custom code" banners.  Because of that setting, Joomla was ignoring the custom banner code, which thankfully DID survive the migration - and Joomla didn't even show the custom banner code fields until I selected the custom code option.  I had to switch that setting back to "custom code" for EVERY banner which made each banner re-appear.  In the _banners table column "type" indicates whether the banner is custom code.  The migration apparently hard codes that to 0 (not custom code) even though custom code is present in the table row, I used SQL queries to change type to 1 (is custom code) for all impacted banners and they resumed working.

**Comment by rasharon** [comment]
I am still seeing the multiple rows per banner client in the banner client display, even with new clients I added after the migration.  So it might be a Joomla defect not a jUpgrade defect.  

Updating any of the multiple displayed rows for one client seems to update the (only) one database row for that client.  So the update appears to work, even though the display doesn't.  I'm guessing the database is ok and its just the display that is defective.

The number of client rows per single client seems to be related to how many banners that client has (or at least influenced by it).

**Comment by fastslack** [comment]
Yes the client migration is missing and im working to a get a patch for this

**Comment by grantiago** [comment]
tnx. what is the source of all the duplicate clients? every time I add a banner it adds a client in the clients tab on the admin side. But there is only one row in the banner_clients table.

**Comment by fastslack** [comment]
This issue is fixed: 264ea2a4cfa345898383bb27cf6332153742e1bb
