### ISSUE TITLE
If database exists, installation fails on error

### ISSUE THREAD

**Issue by mahagr** [fastslack/jUpgrade#3]
<br /><b>jos-Error</b>: JLIB_DATABASE_ERROR_CATEGORY_UNIQUE_ALIAS<br />
JLIB_DATABASE_ERROR_CATEGORY_UNIQUE_ALIAS<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'JUPGRADE_ERROR_INSERTING_CATEGORY' in /var/www-kunena/kunena20js/administrator/components/com_jupgrade/includes/jupgrade.category.class.php:134
Stack trace:
#0 /var/www-kunena/kunena20js/administrator/components/com_jupgrade/includes/controller.php(96): jUpgradeCategory-&gt;upgrade()
#1 {main}

  thrown in <b>/var/www-kunena/kunena20js/administrator/components/com_jupgrade/includes/jupgrade.category.class.php</b> on line <b>134</b><br />

**Comment by mahagr** [comment]
If nothing else, detection & option to delete directory and database would be handy.

**Comment by fastslack** [comment]
Is supposed that the 'cleanup' function deletes all the new tables (j17_). 
Can you send me your mysql dump to reproduce the error?

**Comment by mahagr** [comment]
I was getting it after few failed attempts (notices, warnings), so I don't know what failed.

Currently I'm not testing jUpgrade (got it to work), but will have some new tests soon.

**Comment by mahagr** [comment]
@fastslack here's how you can reproduce it:
- Run jUpgrade
- Run it again

**Comment by fastslack** [comment]
Please check that your mysql user has DROP permission. Check the fix https://github.com/fastslack/jUpgrade/commit/c76fd093fd3164721ba7f3ead5268949e684cb83

**Comment by mahagr** [comment]
Of course it has, I need it in Kunena, too. I will report when I have checked the commit.

**Comment by fastslack** [comment]
Maybe this fix helps: https://github.com/fastslack/jUpgrade/commit/e202313e36aeaa714b82d90d37eaf3f3253aa47e
