### ISSUE TITLE
Issue with Joomla 2.5.6

### ISSUE THREAD

**Issue by rusty1001** [fastslack/jUpgrade#45]
Working fine with 2.5.4 - after joomla upgrade. 
After installation sections does not do "migrate" user undefined (or something like this and holds there,)  the page or mootols tab where it starts working and says importing users is stuck ..."Undefined"

The only way to use is manually upload 2.5.4 files and then run - ticking 'do not download " 

This is in 2.5.1 Jupgrade, I see there is a 2.5.2 release here, not sure if that fixes the issue?

**Comment by fastslack** [comment]
Please try to use the version 2.5.2, the compatibility problem with Joomla 2.5.6 is fixed. If you have any problem let me know.

**Comment by rusty1001** [comment]
Thank you - I will but I did not see 2.5.2 download link, well not on red
component anyway - thanks

On Thu, Jul 12, 2012 at 4:11 PM, Matias Aguirre <
reply@reply.github.com

**Comment by fastslack** [comment]
http://redcomponent.com/free-downloads/cat_view/931-jupgrade

**Comment by rusty1001** [comment]
Thanks matias I did also get new email from redcomponent,
Something to do with me ? :) thanks for the work cheers

On 7/13/12, Matias Aguirre
reply@reply.github.com
wrote:

**Comment by rusty1001** [comment]
Thanks

I am having issues with 2.5.2 and joomla 2.5.6

User undefined and hangs there.

Any ideas,

Thanks

On Fri, Jul 13, 2012 at 3:59 AM, Matias Aguirre <
reply@reply.github.com
