### ISSUE TITLE
Menu item ordering is wrong/random after migration

### ISSUE THREAD

**Issue by mahagr** [fastslack/jUpgrade#6]
Menu items may loose their ordering when they are migrated.

**Comment by fastslack** [comment]
https://github.com/fastslack/jUpgrade/commit/20a7a3ab4fb4dfc3eac5779e733461d500ea0ee1

This patch fix the menu ordering

**Comment by mahagr** [comment]
Why was that line added? I think that it used to fix something -- but what?

Another way would be to order menu items before they get added.

**Comment by fastslack** [comment]
I dont remember why, but it had a reason. Maybe some tree issue..
