### ISSUE TITLE
Menu items are missing some parameters (wrong defaults)

### ISSUE THREAD

**Issue by mahagr** [fastslack/jUpgrade#7]
This is actually Joomla 1.7.3 bug, but you can only see it if you migrate your site from Joomla 1.5.

Some parameters like '''Show Page Heading''' have wrong values unless you save menu items in the new site (no changes are needed, just open and save). In large sites saving each item is a huge task, so it would be best if jUpgrade loaded the defaults just before the params field migration.

**Comment by fastslack** [comment]
Fixed the show page heading issue... do you know other name change in the params?

``` php
diff --git a/trunk/admin/includes/migrate_menus.php b/trunk/admin/includes/migrate_menus.php
index 829d8b9..49314d6 100644
--- a/trunk/admin/includes/migrate_menus.php
+++ b/trunk/admin/includes/migrate_menus.php
@@ -151,6 +151,10 @@ class jUpgradeMenu extends jUpgrade
                                $object->menu_image = '';
                        }
                }
+               if (isset($object->show_page_title)) {
+                       $object->show_page_heading = $object->show_page_title;
+                       unset($object->show_page_title);
+               }
        }

        /**
```

**Comment by mahagr** [comment]
No, I noticed this first and didn't check the others as saving the item seemed to fix the issue.

To me, it looks like show_page_heading and show_page_title are two separate settings (I tried to change both of them). The issue seems to be that Joomla makes checks to the new variable, but has different default value than JForm has.

**Comment by mahagr** [comment]
show_page_title => show_page_heading, just like in the fix. But there are a few other changes as well (didn't check if they are already mapped):
- menu_image = -1 becomes "" (empty string)
- page_heading = (old) page_title
- page_title = (old) page_title (no change in here)

Those allow us to keep the old behavior on menu items.

**Comment by fastslack** [comment]
This patch should help: 13d810b81ac0ddd74517086d38bc910d696fecaa

**Comment by mahagr** [comment]
You misunderstood me. show_page_title must go away, but there are two other changes you need to do, too (in pseudocode):

```
if (menu_image == -1) menu_image = '';
page_heading = page_title;
```

**Comment by fastslack** [comment]
But that corrections really are there...

``` php
    protected function convertParamsHook(&$object)
    {
        if (isset($object->menu_image)) {
            if((string)$object->menu_image == '-1'){
                $object->menu_image = '';
            }
        }
        if (isset($object->show_page_title)) {
            $object->show_page_heading = $object->show_page_title;
        }
    }
```

**Comment by mahagr** [comment]
You're right (I was blind), closing the issue.
