### ISSUE TITLE
Menu Itemids change during migration

### ISSUE THREAD

**Issue by mahagr** [fastslack/jUpgrade#8]
As Joomla accepts non-sef URIs inside articles (and in many other places), all those URIs will break during the migration.

To prevent this, all Itemids must remain the same.

This can be done by changing ids from all the new menu items (id = id + max_old_id) and using the old ids when the old menu items get inserted to the table.

**Comment by mahagr** [comment]
@fastslack: have you thought how easy it would be to fix this one?

**Comment by fastslack** [comment]
@mahagr no yet..any help is welcome :)

**Comment by fastslack** [comment]
@mahagr We are obligated to change the id's because Joomla has 21 menues by default in the installation. Do you like to change the id's of all these defaults menus?

**Comment by mahagr** [comment]
Yes, I believe that Joomla doesn't care what are the ids for the administrator menus, so it would be safe to change the ids.

That Idea needs some testing, though. :)

**Comment by fastslack** [comment]
Hi Matias,

Check this f3a5b4455b4bf79109b2304b800da70bfb1126b7

Also, with this change maybe you need to fix the kunena plugin, you dont need maping any more.

**Comment by mahagr** [comment]
Latest trunk still change all menu items for me.

**Comment by fastslack** [comment]
This patch is working for other users and working on my testings too... check https://github.com/fastslack/jUpgrade/issues/15

**Comment by mahagr** [comment]
I can confirm that this bug has been fixed. You can close this one.

**Comment by fastslack** [comment]
Excellent thanks Matias, closing...
