### ISSUE TITLE
Joomla Versions

### ISSUE THREAD

**Issue by felixkat** [fastslack/jUpgrade#9]
Hi,

I have forked the project and changed the Joomla versions to 1.7 and 2.5.  I assume this is the intention eventually?

I have also removed the one or two references to the 1.6 download as I'm assuming again that this will be replaced by 1.7.

**Comment by fastslack** [comment]
I removed the 1.6 and 1.7 support to release jUpgrade 2.5.0 that will include only Joomla 2.5.0. 
If you have any patch please send a pull request. 
Thanks

**Comment by felixkat** [comment]
So the Github version is for Joomla 2.5 only?

My error, I got confused by the readme.....  ;)

Upgrade is a simple Joomla! 1.5 component that will download a version of Joomla! 1.7/2.5, decompress it and install it. After that, it should migrate all of the data from old Joomla! 1.5 to the new Joomla! 1.7/2.5 installation.

I had some issues with the official release but placing the Github version on top of the existing release and making my mods fixed the issues.  I'll try and identify the issues then and have them changed in the other release.

Thanks

**Comment by fastslack** [comment]
Yes, the next version of jUpgrade (2.5.0) will accept only Joomla! 2.5 migrations. You can see the Joomla! release plan here: http://www.joomlatemplates.co.uk/joomla_templates/img/joomla-development-strategy-en.jpg

Joomla 1.7 has a short life after 2.5 release.

I ll close this issue, thanks for your collaboration.
Regards

**Comment by fastslack** [comment]
Some people told me that they needed to use Joomla 1.7 too so I added your patch to the jupgrade code.
Regards
